Fix/semiloaded state race condition
juspay/hyperswitch-web pull request #164
Opened 2024-02-13 12:49 UTC by vsrivatsa-juspay

2024-02-15 10:36 UTC, prafulkoppalkar requested changes

2024-02-15 10:36 UTC, prafulkoppalkar commented on src/LoaderController.res
> +                setList(._ => payment_methods->Js.Array2.length > 0 ? Loaded(list) : LoadError)
Can you please rewrite this as:

```
let isNonEmptyList  = list->Utils.getDictFromJson->Utils.getArray("payment_methods")->Js.Array2.length > 0
setList(._ =>  isNonEmptyList ? Loaded(list) : LoadError)
```

its more readable

2024-02-15 20:46 UTC, prafulkoppalkar approved these changes

2024-02-16 09:43 UTC, akash-kamble-juspay approved these changes

2024-02-19 07:34 UTC, ArushKapoorJuspay approved these changes

2024-02-19 08:53 UTC, merged