feat: HS-111: Logging framework revamped
juspay/hyperswitch-web pull request #167
Opened 2024-02-14 13:42 UTC by vsrivatsa-juspay

1. Pointed logs to Hyperswitch Vector endpoint
2. Modified payload structure of log requests
3. Added rate limiting over event name
4. Log href of Window.location to help identify integration issues
5. Refactored some logging framework code
6. Removed logs for Dynamic Fields Render

2024-02-15 05:23 UTC, ArushKapoorJuspay commented on src/orca-log-catcher/OrcaLogger.res
> +    Js.log((eventName, updatedCounter, "counter"))
Please remove this log

2024-02-15 05:24 UTC, ArushKapoorJuspay commented on src/orca-log-catcher/OrcaLogger.res
> +      switch eventsCounter.contents->Js.Dict.get(eventName) {
Could you please move this switch in a separate variable to improve code readability

2024-02-15 05:24 UTC, ArushKapoorJuspay commented on src/orca-log-catcher/OrcaLogger.res
> +        switch log.eventName {
Could you please add this value in a separate variable to improve code readability

2024-02-15 05:26 UTC, ArushKapoorJuspay commented on src/orca-log-catcher/OrcaLogger.res
> +    let maxLogsPushedPerEventName = 100
Instead of hardcoding the maxLogsPushed here, should we keep this in webpack for easier configurability @akash-kamble-juspay @prafulkoppalkar

2024-02-15 09:23 UTC, ArushKapoorJuspay submitted a review, later dismissed

2024-02-15 10:26 UTC, prafulkoppalkar requested changes

2024-02-15 10:26 UTC, prafulkoppalkar commented on src/Components/DynamicFields.res
> -
can we keep these logs for few more days ?

2024-02-16 07:47 UTC, prafulkoppalkar submitted a review, later dismissed

2024-02-16 09:48 UTC, akash-kamble-juspay approved these changes

2024-02-16 14:07 UTC, ArushKapoorJuspay approved these changes

2024-02-19 08:41 UTC, prafulkoppalkar approved these changes

2024-02-19 08:59 UTC, merged