fix(animatedcheckbox): Save Card Details checkbox changes
juspay/hyperswitch-web pull request #184
Opened 2024-02-23 10:52 UTC by vsrivatsa-juspay

Hide Save Card Details Checkbox until CustomerPaymentMethodsList responds with is_guest_customer false to prevent payment attempt with setup_future_usage: "on_session" when customer_id is actually null

fixes #183

2024-02-26 07:05 UTC, ArushKapoorJuspay approved these changes

2024-02-26 17:20 UTC, Narayanbhat166 approved these changes

2024-02-27 07:12 UTC, prafulkoppalkar requested changes
Please resolve the comments

2024-02-27 07:12 UTC, prafulkoppalkar commented on src/Types/PaymentType.res
why do you even need this bool? 
in both the variants .. cant this be solved by just by storing isGuestCustomer in a recoil and use it were ever needed

2024-02-27 08:47 UTC, prafulkoppalkar commented on src/Types/PaymentType.res
then this is not even needed right you can just add this prop in item to obj mapper and get access to the value

2024-02-27 09:24 UTC, prafulkoppalkar approved these changes

2024-02-27 09:25 UTC, merged