Refactor/lazy load locale strings
juspay/hyperswitch-web pull request #263
Opened 2024-03-28 08:28 UTC by seekshiva

## Type of Change

- [x] Enhancement
- [x] Refactoring

## Description

Lazy load localeStrings instead of adding it as part of main bundle.

## Motivation and Context

As we add support for more locales, it bloats up our bundle size. We can bundle a default locale (en) as part of main bundle, and lazy load everything else.

## How did you test it?

-

## Checklist

- [x] I ran `npm run re:build`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible

2024-04-04 12:28 UTC, vsrivatsa-juspay commented on src/LocaleStrings/LocaleStringHelper.res
> +  | "en" => EN
```suggestion
```

2024-04-04 12:28 UTC, vsrivatsa-juspay commented on src/LocaleStrings/LocaleStringHelper.res
> +  | "ru" => RU
```suggestion
  | "ru" => RU
  | "en"
```

2024-04-04 12:29 UTC, vsrivatsa-juspay commented on src/LocaleStrings/SwedishLocale.res
> +  on: "på",
```suggestion
  on: `på`,
```

2024-04-04 12:30 UTC, vsrivatsa-juspay commented on src/LocaleStrings/ArabicLocale.res
> +  saveWalletDetails: "سيتم حفظ تفاصيل المحفظة عند الاختيار",
```suggestion
  saveWalletDetails: `سيتم حفظ تفاصيل المحفظة عند الاختيار`,
```

2024-04-04 12:31 UTC, vsrivatsa-juspay commented on src/LocaleStrings/DeutschLocale.res
> +  saveWalletDetails: "Wallet-Details werden beim Auswählen gespeichert",
```suggestion
  saveWalletDetails: `Wallet-Details werden beim Auswählen gespeichert`,
```

2024-04-04 12:32 UTC, vsrivatsa-juspay commented on src/LocaleStrings/FrenchLocale.res
> +  saveWalletDetails: "Les détails du portefeuille seront enregistrés lors de la sélection",
```suggestion
  saveWalletDetails: `Les détails du portefeuille seront enregistrés lors de la sélection`,
```

2024-04-04 12:32 UTC, vsrivatsa-juspay commented on src/LocaleStrings/HebrewLocale.res
> +  saveWalletDetails: "פרטי הארנק יישמרו בעת בחירה",
```suggestion
  saveWalletDetails: `פרטי הארנק יישמרו בעת בחירה`,
```

2024-04-04 12:32 UTC, vsrivatsa-juspay commented on src/LocaleStrings/JapaneseLocale.res
> +  currencyLabel: "通貨",
```suggestion
  currencyLabel: `通貨`,
```

2024-04-04 12:32 UTC, vsrivatsa-juspay commented on src/LocaleStrings/JapaneseLocale.res
> +  saveWalletDetails: "選択時にウォレットの詳細が保存されます",
```suggestion
  saveWalletDetails: `選択時にウォレットの詳細が保存されます`,
```

2024-04-04 12:33 UTC, vsrivatsa-juspay commented on src/LocaleStrings/SwedishLocale.res
> +  stateEmptyText: "Staten får inte vara tom",
```suggestion
  stateEmptyText: `Staten får inte vara tom`,
```

2024-04-04 12:34 UTC, vsrivatsa-juspay requested changes
Please address comments

2024-04-05 07:16 UTC, prafulkoppalkar submitted a review, later dismissed

2024-04-05 07:19 UTC, PritishBudhiraja commented on src/LocaleStrings/LocaleStringHelper.res
> +  | "ru" => RU
Resolved

2024-04-05 07:19 UTC, PritishBudhiraja commented on src/LocaleStrings/SwedishLocale.res
> +  on: "på",
Resolved

2024-04-05 07:19 UTC, PritishBudhiraja commented on src/LocaleStrings/DeutschLocale.res
> +  saveWalletDetails: "Wallet-Details werden beim Auswählen gespeichert",
Resolved

2024-04-05 07:20 UTC, PritishBudhiraja commented on src/LocaleStrings/FrenchLocale.res
> +  saveWalletDetails: "Les détails du portefeuille seront enregistrés lors de la sélection",
Resolved

2024-04-05 07:20 UTC, PritishBudhiraja commented on src/LocaleStrings/HebrewLocale.res
> +  saveWalletDetails: "פרטי הארנק יישמרו בעת בחירה",
Resolved

2024-04-05 07:21 UTC, PritishBudhiraja commented on src/LocaleStrings/JapaneseLocale.res
> +  currencyLabel: "通貨",
Resolved

2024-04-05 07:21 UTC, PritishBudhiraja commented on src/LocaleStrings/ArabicLocale.res
> +  saveWalletDetails: "سيتم حفظ تفاصيل المحفظة عند الاختيار",
Resolved

2024-04-05 07:22 UTC, PritishBudhiraja commented on src/LocaleStrings/JapaneseLocale.res
> +  saveWalletDetails: "選択時にウォレットの詳細が保存されます",
Resolved

2024-04-05 07:22 UTC, PritishBudhiraja commented on src/LocaleStrings/SwedishLocale.res
> +  stateEmptyText: "Staten får inte vara tom",
Resolved

2024-04-05 07:24 UTC, PritishBudhiraja approved these changes

2024-04-05 07:35 UTC, prafulkoppalkar approved these changes

2024-04-08 12:05 UTC, vsrivatsa-juspay approved these changes

2024-04-10 10:49 UTC, merged