fix: added Loader and Error Handling for TrustPay GooglePay
juspay/hyperswitch-web pull request #268
Opened 2024-04-03 08:28 UTC by ArushKapoorJuspay

## Type of Change

- [x] Bugfix
- [ ] New feature
- [x] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

1. Added Background Loader once TrustPay GooglePay button is clicked.
2. Added polling and timeout for TrustPay GooglePay

## How did you test it?

Tested transactions via TrustPay GooglePay

## Checklist

- [x] I ran `npm run re:build`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible

2024-04-03 10:31 UTC, vsrivatsa-juspay commented on src/orca-loader/Elements.res
> +                      Utils.delay(600000)->then(_ => resolve(Dict.make()->JSON.Encode.object))
Is this supposed to be 1m or 10m?

2024-04-03 10:31 UTC, vsrivatsa-juspay commented on src/orca-loader/Elements.res
> +                        ~value="TrustPay GooglePay Success Response",
If timeout is resolved first, the log shouldn't be TrustPay GooglePay Success Response

2024-04-03 10:32 UTC, vsrivatsa-juspay commented on src/orca-loader/Elements.res
> +                        ~value="TrustPay GooglePay Success Response",
Resolve timeOut promise with a failure string.
Decode res and check if it matches the failure string, and branch out the handling

2024-04-03 10:33 UTC, vsrivatsa-juspay requested changes
Please resolve comments

2024-04-04 08:41 UTC, prafulkoppalkar approved these changes

2024-04-04 08:41 UTC, merged