fix: HS-165: custom backend url fix with prelim check on sentry url
juspay/hyperswitch-web pull request #27
Opened 2023-11-16 12:00 UTC by arun-mi

2023-11-16 14:28 UTC, prafulkoppalkar commented on src/orca-loader/Elements.res
> +    let endpoint = ApiEndpoint.getApiEndPoint()
i think we should pass pub key here to determines wether it is in test mode or not ..

2023-11-16 14:28 UTC, prafulkoppalkar requested changes
please address the comments

2023-11-16 17:20 UTC, prafulkoppalkar approved these changes

2023-11-17 05:36 UTC, akash-kamble-juspay approved these changes

2023-11-17 05:42 UTC, merged