feat: HS-167: Added Open Banking UK Payment Method
juspay/hyperswitch-web pull request #30
Opened 2023-11-19 23:27 UTC by ArushKapoorJuspay

**Problem Description -** Add Open Banking UK Payment Method

**Sample Confirm Request Body -**

```
"payment_method": "bank_redirect",
  "payment_method_type": "open_banking_uk",
  "payment_method_data": {
    "bank_redirect": {
      "open_banking_uk": {
        "issuer": "citi",
        "country": "GB"
    }
  }
},
```

2023-11-22 09:59 UTC, arun-mi commented on src/Payments/PaymentMethodsWrapper.res
> +          let selectedBankInSnakeCase =
Why is there a requirement for doing this?

2023-11-22 10:01 UTC, arun-mi commented on src/Utilities/Utils.res
> +      arr->Js.Array2.push(bankName->getPascalCaseWithSpaceFromSnakeCase)->ignore
Any reason why we need to convert to Pascal case from Snake Case?

2023-11-23 10:30 UTC, arun-mi requested changes
Requesting testing with non-english texts for pascal case conversion

2023-11-23 12:39 UTC, arun-mi approved these changes

2023-11-23 12:40 UTC, akash-kamble-juspay approved these changes

2023-11-23 12:40 UTC, merged