fix: remove expired saved cards
juspay/hyperswitch-web pull request #345
Opened 2024-05-02 09:18 UTC by PritishBudhiraja

## Type of Change

- [x] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

We were able to see saved cards which were expired. Filtered from fronted to don't see the expired cards.

## How did you test it?

Check for expired cards in locker and these shouldn't come in Saved PM Screen.

## Checklist

- [x] I ran `npm run re:build`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible

2024-05-02 09:34 UTC, vsrivatsa25 requested changes
Card is valid through the card.expiryMonth. Need to compare with next expiryMonth + 1 or expiryYear + 1 if expiryMonth == 12

2024-05-02 09:56 UTC, vsrivatsa25 commented on src/PaymentElement.res
> +            let expiryDate = Date.fromString(`${expiryYear}-${expiryMonth}-01`)
```suggestion
            let expiryDate = Date.fromString(`${expiryYear}-${expiryMonth}`)
```

2024-05-02 09:57 UTC, vsrivatsa25 commented on src/PaymentElement.res
> +            expiryDate > currentDate
```suggestion
            expiryDate >= currentDate
```

2024-05-02 10:06 UTC, vsrivatsa25 approved these changes

2024-05-03 06:29 UTC, vsrivatsa-juspay commented on src/Components/SavedCardItem.res
> +  let isCardExpired = isCard ? expiryDate < currentDate : false
```suggestion
  let isCardExpired = isCard && expiryDate < currentDate
```

2024-05-03 06:30 UTC, vsrivatsa-juspay commented on src/Components/SavedCardItem.res
> +            <RenderIf condition={isCard && isCardExpired}>
```suggestion
            <RenderIf condition={isCardExpired}>
```
isCardExpired already checks off isCard

2024-05-03 06:46 UTC, vsrivatsa-juspay approved these changes

2024-05-03 10:56 UTC, ArushKapoorJuspay approved these changes

2024-05-03 11:02 UTC, ArushKapoorJuspay approved these changes

2024-05-03 11:02 UTC, merged