Pm collect
juspay/hyperswitch-web pull request #435
Opened 2024-06-10 16:35 UTC by kashif-m

## Type of Change

- [ ] Bugfix
- [ ] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

## How did you test it?

## Checklist

- [ ] I ran `npm run re:build`
- [ ] I reviewed submitted code
- [ ] I added unit tests for my changes where possible

2024-06-14 13:02 UTC, PritishBudhiraja approved these changes

2024-06-14 13:06 UTC, PritishBudhiraja requested changes
Requested

2024-06-24 09:34 UTC, ArushKapoorJuspay approved these changes

2024-06-24 09:36 UTC, PritishBudhiraja approved these changes

2024-06-25 12:02 UTC, merged