feat: pass email and phone number to confirm call
juspay/hyperswitch-web pull request #681
Opened 2024-09-24 12:58 UTC by ImSagnik007

Pass email and phone number to confirm call

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description
Passing email address and phone number for paypal in confirm call, for apple pay and klarna it is already getting passed.

## How did you test it?

## Checklist

- [x] I ran `npm run re:build`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible

2024-09-24 13:17 UTC, ArushKapoorJuspay commented on src/Utilities/DynamicFieldsUtils.res
> +      | "payment_method_data.billing.email"
Is there some other way instead of hard coding the path. Since later on if this path gets changed from the backend, this code will start breaking?

2024-09-25 11:22 UTC, ArushKapoorJuspay approved these changes

2024-09-25 11:24 UTC, ArushKapoorJuspay requested changes

2024-09-25 11:24 UTC, ArushKapoorJuspay commented on src/Payments/PaypalSDKHelpers.res
> +              %debugger
Please remove the debugger

2024-09-25 11:25 UTC, ArushKapoorJuspay approved these changes

2024-09-26 12:31 UTC, PritishBudhiraja approved these changes

2024-09-26 12:36 UTC, merged