feat: HS-181: Added support of Dynamic Fields For Bancontact
juspay/hyperswitch-web pull request #72
Opened 2023-12-15 10:26 UTC by ArushKapoorJuspay

**Problem Description -** Required support of Dynamic Fields for Bancontact

**Solution -** Moved cards to Dynamic Fields only for Bancontact

2024-01-11 05:11 UTC, prafulkoppalkar approved these changes

2024-01-11 09:23 UTC, arun-mi requested changes

2024-01-11 09:23 UTC, arun-mi commented on src/Components/DynamicFields.res
> +          <div
Can you put a check for when there are no billing fields to show?

2024-01-11 09:23 UTC, arun-mi commented on src/Components/DynamicFields.res
> +                  pattern="[\d| ]{16,22}"
Can you remove these patterns whenever you find>? These throw errors.

2024-01-12 08:50 UTC, arun-mi commented on src/Components/DynamicFields.res
> +    ~setAreRequiredFieldsEmpty,
The above recoil states can be pulled by the hook itself instead of passing it as props

2024-01-16 07:46 UTC, arun-mi commented on src/CardUtils.res
> +let getCardDetailsHook = (~cvcNumber, ~isCvcValidValue, ~isCVCValid) => {
Custom hooks needs to start with 'use' by best practice for clear demarcation so nobody uses it like a function.

2024-01-16 07:51 UTC, arun-mi commented on src/Components/DynamicFields.res
> +
The above has to handle the zero fields usecase for when dynamic fields required is none.

2024-01-16 07:53 UTC, arun-mi commented on src/Components/DynamicFields.res
> +              className="dynamic__fields p-2"
Can you verify where this class name is from and what this does?

2024-01-16 09:53 UTC, arun-mi approved these changes

2024-01-16 10:38 UTC, akash-kamble-juspay approved these changes

2024-01-16 10:58 UTC, merged