FEAT: klarna Checkout SDK added
juspay/hyperswitch-web pull request #851
Opened 2024-12-26 10:24 UTC by Sweta-Kumari-Sharma

#850

## Type of Change

- [ ] Bugfix
- [x] New feature
- [ ] Enhancement
- [ ] Refactoring
- [ ] Dependency updates
- [ ] Documentation
- [ ] CI/CD

## Description

## How did you test it?

Payment data used in ```server.js``` for ```create-payment-intent``` call:
```
const paymentData = {
  amount: 50000,
  order_tax_amount: 0,
  confirm: false,
  currency: "USD",
  capture_method: "automatic",
  customer_id: "klarna",
  payment_experience: "redirect_to_url",
  capture_on: "2022-09-10T10:11:12Z",
  authentication_type: "no_three_ds",
  billing: {
    address: {
      line1: "1467",
      line2: "Harrison Street",
      line3: "Harrison Street",
      city: "San Francisco",
      state: "California",
      zip: "94122",
      country: "US",
      first_name: "joseph",
      last_name: "Doe"
    },
    phone: {
      number: "8056594427",
      country_code: "+91"
    },
    email: "guest@example.com"
  },
  order_details: [
    {
      product_name: "Red T-Shirt",
      quantity: 5,
      amount: 10000,
      account_name: "transaction_processing",
      total_tax_amount: 0,
      tax_rate: 0,
      total_amount: 50000
    }
  ],
  email: "guest@example.com",
  name: "John Doe",
  phone: "999999999",
  phone_country_code: "+65",
  description: "Its my first payment request",
  return_url: "https://google.com/"
};
```

https://github.com/user-attachments/assets/45fa050b-1dd4-438f-8c68-a7022e38b9f7

klarna Kustom Checkout connector endpoint doesn't accept ```return_url``` without ```https```, that's why I tested by using [https://www.google.com] as the ```return_url```.

## Checklist

- [x] I ran `npm run re:build`
- [x] I reviewed submitted code
- [ ] I added unit tests for my changes where possible

2024-12-26 10:33 UTC, ImSagnik007 requested changes

2024-12-26 10:33 UTC, ImSagnik007 commented on Hyperswitch-React-Demo-App/src/CheckoutForm.js
> +import { ExpressCheckoutElement, PaymentElement } from "@juspay-tech/react-hyper-js";
undo the file changes

2024-12-26 12:24 UTC, PritishBudhiraja requested changes
I guess loader need to be off full screen that is coming only in the button error. And can you also handle the case when let's say I have Klarna Element and Payment Element both in a page what will happen.

2024-12-26 12:24 UTC, PritishBudhiraja commented on src/WalletElement.res
> -
remove this file.

2024-12-26 12:24 UTC, PritishBudhiraja commented on src/Utilities/PaymentBody.res
> +]
```suggestion
let klarnaCheckoutBody = (~connectors) => {
  open Utils
  let payLaterBody = [("klarna_checkout", JSON.Encode.null)]->getJsonFromArrayOfJson
  let paymentMethodData = [("pay_later", payLaterBody)]->getJsonFromArrayOfJson

  [
    ("payment_method", "pay_later"->JSON.Encode.string),
    ("payment_method_type", "klarna"->JSON.Encode.string),
    ("payment_experience", "redirect_to_url"->JSON.Encode.string),
    ("connector", connectors->getArrofJsonString->JSON.Encode.array),
    ("payment_method_data", paymentMethodData),
  ]
}
```

2024-12-26 12:24 UTC, PritishBudhiraja commented on src/Payments/PaymentRequestButtonElement.res
> +
```suggestion
  let {isKlarnaSDKFlow, isKlarnaCheckoutFlow} = KlarnaHelpers.usePaymentMethodExperience(
    ~paymentMethodListValue,
    ~sessionObj,
  )
```

2024-12-26 12:24 UTC, PritishBudhiraja commented on src/Payments/KlarnaCheckout.res
> +    Utils.makeOneClickHandlerPromise(sdkHandleIsThere)
try using async await we are moving to that using. Can you try this.

2024-12-26 12:24 UTC, PritishBudhiraja commented on src/Payments/KlarnaCheckout.res
> +    onClick={_ => options.readOnly ? () : onKlarnaClick()}>
```suggestion
  onClick={_ =>
      if !options.readOnly {
        onKlarnaClick()
      }}
```

2024-12-26 12:24 UTC, PritishBudhiraja commented on src/Payments/KlarnaCheckout.res
> +      }}
```suggestion
      {if klarnaClicked {
            <Loader />
      } else {
      klarnaIcon
      }}
```

2024-12-27 16:10 UTC, Sweta-Kumari-Sharma commented
> I guess loader need to be off full screen that is coming only in the button error. And can you also handle the case when let's say I have Klarna Element and Payment Element both in a page what will happen.

I took reference from Paypal's redirection flow, in that also loader was shown above button only

https://github.com/user-attachments/assets/32ac22c8-5978-4828-a0da-b9441990f546

And this is how the UI looks when Payment Element is rendered as well
<img width="1725" alt="Screenshot 2024-12-27 at 9 37 51 PM" src="https://github.com/user-attachments/assets/af382731-cd1e-4def-8ee5-897b06b1e9f4" />

2024-12-27 21:58 UTC, PritishBudhiraja approved these changes

2024-12-31 07:15 UTC, seekshiva submitted a review, later dismissed

2025-01-01 15:40 UTC, ImSagnik007 approved these changes

2025-01-02 08:47 UTC, sakksham7 commented on src/Payments/KlarnaHelpers.res
> +type paypalExperienceData = {
```suggestion
type klarnaExperienceData = {
```

2025-01-02 09:08 UTC, PritishBudhiraja submitted a review, later dismissed

2025-01-03 05:38 UTC, sakksham7 submitted a review, later dismissed

2025-01-03 06:13 UTC, aritro2002 commented on src/Utilities/PaymentUtils.res
> +        }
The logic can be simplified by combining the conditions using an || operator. Instead of duplicating the same action in both if and else if blocks, you can write
```
if (isKlarnaSDKFlow && isShowKlarnaOneClick && isInvokeSDKExperience) || isRedirectExperience {
          walletsList->Array.push(item.paymentMethodName)->ignore
        }
```
The remaining code looks good to me.

2025-01-03 06:47 UTC, ImSagnik007 submitted a review, later dismissed

2025-01-03 07:02 UTC, PritishBudhiraja approved these changes

2025-01-03 07:02 UTC, sakksham7 approved these changes

2025-01-03 07:04 UTC, aritro2002 approved these changes

2025-01-03 07:07 UTC, merged